# Generated by Django 5.2.7 on 2025-10-23 18:42

import archerydjango.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("junior_rankings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="shot_round",
            field=archerydjango.fields.RoundField(
                max_length=64,
                rounds=[
                    "metric_i",
                    "metric_ii",
                    "metric_iii",
                    "metric_iv",
                    "metric_v",
                    "metric_122_50",
                    "metric_122_40",
                    "metric_122_30",
                    "metric_80_50",
                    "metric_80_40",
                    "metric_80_30",
                    "agb900_70",
                    "agb900_60",
                    "agb900_50",
                    "agb900_40",
                    "agb900_30",
                    "york",
                    "hereford",
                    "bristol_i",
                    "bristol_ii",
                    "bristol_iii",
                    "bristol_iv",
                    "bristol_v",
                    "st_george",
                    "albion",
                    "windsor",
                    "windsor_50",
                    "windsor_40",
                    "windsor_30",
                ],
            ),
        ),
        migrations.AlterField(
            model_name="submissionscore",
            name="shot_round",
            field=archerydjango.fields.RoundField(
                max_length=64,
                rounds=[
                    "metric_i",
                    "metric_ii",
                    "metric_iii",
                    "metric_iv",
                    "metric_v",
                    "metric_122_50",
                    "metric_122_40",
                    "metric_122_30",
                    "metric_80_50",
                    "metric_80_40",
                    "metric_80_30",
                    "agb900_70",
                    "agb900_60",
                    "agb900_50",
                    "agb900_40",
                    "agb900_30",
                    "york",
                    "hereford",
                    "bristol_i",
                    "bristol_ii",
                    "bristol_iii",
                    "bristol_iv",
                    "bristol_v",
                    "st_george",
                    "albion",
                    "windsor",
                    "windsor_50",
                    "windsor_40",
                    "windsor_30",
                ],
            ),
        ),
    ]
