# Generated by Django 5.2.7 on 2025-10-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("junior_rankings", "0002_alter_score_shot_round_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("agb_number", models.CharField(max_length=256)),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("processed", models.BooleanField(default=False)),
            ],
        ),
    ]
