# Generated by Django 5.2.7 on 2025-11-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("junior_rankings", "0003_contactresponse"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="extranet_id",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
    ]
