# Generated by Django 5.2.7 on 2025-11-04 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "junior_rankings",
            "0005_event_round_age_rules_alter_score_shot_round_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="agb_number",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="bowstyle",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="forename",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="surname",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="year",
        ),
        migrations.AddField(
            model_name="submission",
            name="athlete_season",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="junior_rankings.athleteseason",
            ),
            preserve_default=False,
        ),
    ]
