# Generated by Django 5.2.8 on 2025-11-18 22:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("junior_rankings", "0006_remove_submission_agb_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="submitted",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
