# Generated by Django 6.0 on 2025-12-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("junior_rankings", "0007_submission_submitted"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="processed",
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="submissionscore",
            name="accepted",
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="submissionscore",
            name="rejected",
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
