# Generated by Django 6.0 on 2025-12-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("junior_rankings", "0008_submission_saving"),
    ]

    operations = [
        migrations.AddField(
            model_name="athleteseason",
            name="age_group_rank",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="athleteseason",
            name="age_group_rank_is_equal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="athleteseason",
            name="agg_handicap",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="athleteseason",
            name="overall_rank",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="athleteseason",
            name="overall_rank_is_equal",
            field=models.BooleanField(default=False),
        ),
    ]
